// ─────────────────────────────────────────────
// AisleUtils
// Grocery aisle classification for shopping
// list items. Maps ingredient names to store
// sections for aisle-based grouping.
// ─────────────────────────────────────────────

/// Grocery store aisle / section.
enum GroceryAisle {
  produce,
  meatAndFish,
  dairy,
  bakery,
  tinsAndDry,
  condiments,
  spices,
  frozen,
  drinks,
  other,
}

class AisleUtils {
  AisleUtils._();

  /// Display names for each aisle, keyed by enum value.
  static const Map<GroceryAisle, String> _displayNames = {
    GroceryAisle.produce: 'Produce',
    GroceryAisle.meatAndFish: 'Meat & Fish',
    GroceryAisle.dairy: 'Dairy & Eggs',
    GroceryAisle.bakery: 'Bakery',
    GroceryAisle.tinsAndDry: 'Tins & Dry Goods',
    GroceryAisle.condiments: 'Condiments & Sauces',
    GroceryAisle.spices: 'Herbs & Spices',
    GroceryAisle.frozen: 'Frozen',
    GroceryAisle.drinks: 'Drinks',
    GroceryAisle.other: 'Other',
  };

  /// Returns the human-readable display name for an aisle.
  static String displayName(GroceryAisle aisle) => _displayNames[aisle]!;

  /// Returns aisles in the default order they should appear in the UI.
  ///
  /// Default order = enum declaration order. For per-user custom
  /// orderings (Sprint 16.7c), call [orderedFor] with the user's
  /// stored preference instead.
  static List<GroceryAisle> get displayOrder => GroceryAisle.values;

  /// Returns aisles in the user's preferred order. Sprint 16.7c — backs
  /// the long-press-and-drag reorder UX on the shopping list. The user
  /// preference is a list of [GroceryAisle.name] strings persisted on
  /// `users/{uid}.aisleOrder`.
  ///
  /// Behaviour:
  ///   • null or empty preference → falls back to the default enum order.
  ///   • Unknown aisle names in the preference → silently dropped.
  ///   • Known names not present in the preference → appended at the end
  ///     in the default enum order. Newly-added aisles in future schema
  ///     versions inherit a sensible default rather than vanishing.
  ///   • Repeats in the preference → deduplicated; first occurrence wins.
  static List<GroceryAisle> orderedFor(List<String>? preference) {
    if (preference == null || preference.isEmpty) {
      return GroceryAisle.values;
    }
    final byName = {for (final a in GroceryAisle.values) a.name: a};
    final ordered = <GroceryAisle>[];
    final seen = <GroceryAisle>{};
    for (final name in preference) {
      final aisle = byName[name];
      if (aisle != null && seen.add(aisle)) {
        ordered.add(aisle);
      }
    }
    for (final aisle in GroceryAisle.values) {
      if (!seen.contains(aisle)) ordered.add(aisle);
    }
    return ordered;
  }

  /// Keyword → aisle mapping. Ordered from most specific to least specific
  /// so that multi-word phrases match before their individual words.
  ///
  /// ~180 keywords covering common UK and US ingredient names.
  static const List<MapEntry<String, GroceryAisle>> _keywords = [
    // ── Frozen (check before produce/dairy to catch "frozen X") ──
    MapEntry('frozen pea', GroceryAisle.frozen),
    MapEntry('frozen sweetcorn', GroceryAisle.frozen),
    MapEntry('frozen corn', GroceryAisle.frozen),
    MapEntry('frozen berr', GroceryAisle.frozen),
    MapEntry('frozen fruit', GroceryAisle.frozen),
    MapEntry('frozen chip', GroceryAisle.frozen),
    MapEntry('frozen fries', GroceryAisle.frozen),
    MapEntry('frozen pizza', GroceryAisle.frozen),
    MapEntry('frozen veg', GroceryAisle.frozen),
    MapEntry('frozen fish', GroceryAisle.frozen),
    MapEntry('frozen prawn', GroceryAisle.frozen),
    MapEntry('frozen shrimp', GroceryAisle.frozen),
    MapEntry('frozen chicken', GroceryAisle.frozen),
    MapEntry('frozen spinach', GroceryAisle.frozen),
    MapEntry('frozen bread', GroceryAisle.frozen),
    MapEntry('ice cream', GroceryAisle.frozen),
    MapEntry('ice lolly', GroceryAisle.frozen),
    MapEntry('ice lollies', GroceryAisle.frozen),
    MapEntry('fish finger', GroceryAisle.frozen),
    MapEntry('fish stick', GroceryAisle.frozen),
    MapEntry('frozen', GroceryAisle.frozen),

    // ── Drinks (before dairy — "oat milk" etc. are drinks) ──
    MapEntry('oat milk', GroceryAisle.drinks),
    MapEntry('almond milk', GroceryAisle.drinks),
    MapEntry('coconut milk', GroceryAisle.drinks),
    MapEntry('soy milk', GroceryAisle.drinks),
    MapEntry('soya milk', GroceryAisle.drinks),
    MapEntry('rice milk', GroceryAisle.drinks),
    MapEntry('cashew milk', GroceryAisle.drinks),
    MapEntry('hemp milk', GroceryAisle.drinks),
    MapEntry('orange juice', GroceryAisle.drinks),
    MapEntry('apple juice', GroceryAisle.drinks),
    MapEntry('cranberry juice', GroceryAisle.drinks),
    MapEntry('grape juice', GroceryAisle.drinks),
    MapEntry('pineapple juice', GroceryAisle.drinks),
    MapEntry('fruit juice', GroceryAisle.drinks),
    MapEntry('juice', GroceryAisle.drinks),
    MapEntry('squash cordial', GroceryAisle.drinks),
    MapEntry('squash drink', GroceryAisle.drinks),
    MapEntry('cordial', GroceryAisle.drinks),
    MapEntry('lemonade', GroceryAisle.drinks),
    MapEntry('cola', GroceryAisle.drinks),
    MapEntry('sparkling water', GroceryAisle.drinks),
    MapEntry('mineral water', GroceryAisle.drinks),
    MapEntry('tonic water', GroceryAisle.drinks),
    MapEntry('soda water', GroceryAisle.drinks),
    MapEntry('kombucha', GroceryAisle.drinks),
    MapEntry('smoothie', GroceryAisle.drinks),
    MapEntry('energy drink', GroceryAisle.drinks),

    // ── Condiments & Sauces (before produce — "tomato paste" etc.) ──
    MapEntry('tomato paste', GroceryAisle.condiments),
    MapEntry('tomato puree', GroceryAisle.condiments),
    MapEntry('tomato purée', GroceryAisle.condiments),
    MapEntry('tomato sauce', GroceryAisle.condiments),
    MapEntry('tomato ketchup', GroceryAisle.condiments),
    MapEntry('passata', GroceryAisle.condiments),
    MapEntry('lemon juice', GroceryAisle.condiments),
    MapEntry('lime juice', GroceryAisle.condiments),
    MapEntry('olive oil', GroceryAisle.condiments),
    MapEntry('vegetable oil', GroceryAisle.condiments),
    MapEntry('sunflower oil', GroceryAisle.condiments),
    MapEntry('rapeseed oil', GroceryAisle.condiments),
    MapEntry('canola oil', GroceryAisle.condiments),
    MapEntry('sesame oil', GroceryAisle.condiments),
    MapEntry('coconut oil', GroceryAisle.condiments),
    MapEntry('avocado oil', GroceryAisle.condiments),
    MapEntry('cooking oil', GroceryAisle.condiments),
    MapEntry('oil', GroceryAisle.condiments),
    MapEntry('balsamic vinegar', GroceryAisle.condiments),
    MapEntry('white wine vinegar', GroceryAisle.condiments),
    MapEntry('red wine vinegar', GroceryAisle.condiments),
    MapEntry('apple cider vinegar', GroceryAisle.condiments),
    MapEntry('rice vinegar', GroceryAisle.condiments),
    MapEntry('malt vinegar', GroceryAisle.condiments),
    MapEntry('vinegar', GroceryAisle.condiments),
    MapEntry('soy sauce', GroceryAisle.condiments),
    MapEntry('fish sauce', GroceryAisle.condiments),
    MapEntry('oyster sauce', GroceryAisle.condiments),
    MapEntry('worcestershire', GroceryAisle.condiments),
    MapEntry('tabasco', GroceryAisle.condiments),
    MapEntry('sriracha', GroceryAisle.condiments),
    MapEntry('hot sauce', GroceryAisle.condiments),
    MapEntry('chilli sauce', GroceryAisle.condiments),
    MapEntry('chili sauce', GroceryAisle.condiments),
    MapEntry('sweet chilli', GroceryAisle.condiments),
    MapEntry('sweet chili', GroceryAisle.condiments),
    MapEntry('hoisin', GroceryAisle.condiments),
    MapEntry('teriyaki', GroceryAisle.condiments),
    MapEntry('bbq sauce', GroceryAisle.condiments),
    MapEntry('barbecue sauce', GroceryAisle.condiments),
    MapEntry('ketchup', GroceryAisle.condiments),
    MapEntry('mustard', GroceryAisle.condiments),
    MapEntry('mayo', GroceryAisle.condiments),
    MapEntry('mayonnaise', GroceryAisle.condiments),
    MapEntry('pesto', GroceryAisle.condiments),
    MapEntry('curry paste', GroceryAisle.condiments),
    MapEntry('thai paste', GroceryAisle.condiments),
    MapEntry('harissa', GroceryAisle.condiments),
    MapEntry('tahini', GroceryAisle.condiments),
    MapEntry('miso paste', GroceryAisle.condiments),
    MapEntry('miso', GroceryAisle.condiments),
    MapEntry('peanut butter', GroceryAisle.condiments),
    MapEntry('almond butter', GroceryAisle.condiments),
    MapEntry('cashew butter', GroceryAisle.condiments),
    MapEntry('jam', GroceryAisle.condiments),
    MapEntry('marmalade', GroceryAisle.condiments),
    MapEntry('honey', GroceryAisle.condiments),
    MapEntry('maple syrup', GroceryAisle.condiments),
    MapEntry('golden syrup', GroceryAisle.condiments),
    MapEntry('treacle', GroceryAisle.condiments),
    MapEntry('molasses', GroceryAisle.condiments),
    MapEntry('relish', GroceryAisle.condiments),
    MapEntry('pickle', GroceryAisle.condiments),
    MapEntry('chutney', GroceryAisle.condiments),
    MapEntry('salad dressing', GroceryAisle.condiments),
    MapEntry('ranch', GroceryAisle.condiments),

    // ── Tins & Dry Goods (before produce — "tinned tomatoes" etc.) ──
    MapEntry('tinned tomato', GroceryAisle.tinsAndDry),
    MapEntry('canned tomato', GroceryAisle.tinsAndDry),
    MapEntry('chopped tomato', GroceryAisle.tinsAndDry),
    MapEntry('plum tomato', GroceryAisle.tinsAndDry),
    MapEntry('tinned', GroceryAisle.tinsAndDry),
    MapEntry('canned', GroceryAisle.tinsAndDry),
    MapEntry('pasta', GroceryAisle.tinsAndDry),
    MapEntry('spaghetti', GroceryAisle.tinsAndDry),
    MapEntry('penne', GroceryAisle.tinsAndDry),
    MapEntry('fusilli', GroceryAisle.tinsAndDry),
    MapEntry('macaroni', GroceryAisle.tinsAndDry),
    MapEntry('tagliatelle', GroceryAisle.tinsAndDry),
    MapEntry('linguine', GroceryAisle.tinsAndDry),
    MapEntry('lasagne sheet', GroceryAisle.tinsAndDry),
    MapEntry('lasagna sheet', GroceryAisle.tinsAndDry),
    MapEntry('orzo', GroceryAisle.tinsAndDry),
    MapEntry('rice', GroceryAisle.tinsAndDry),
    MapEntry('basmati', GroceryAisle.tinsAndDry),
    MapEntry('jasmine rice', GroceryAisle.tinsAndDry),
    MapEntry('risotto rice', GroceryAisle.tinsAndDry),
    MapEntry('arborio', GroceryAisle.tinsAndDry),
    MapEntry('noodle', GroceryAisle.tinsAndDry),
    MapEntry('egg noodle', GroceryAisle.tinsAndDry),
    MapEntry('rice noodle', GroceryAisle.tinsAndDry),
    MapEntry('udon', GroceryAisle.tinsAndDry),
    MapEntry('ramen', GroceryAisle.tinsAndDry),
    MapEntry('couscous', GroceryAisle.tinsAndDry),
    MapEntry('quinoa', GroceryAisle.tinsAndDry),
    MapEntry('bulgur', GroceryAisle.tinsAndDry),
    MapEntry('polenta', GroceryAisle.tinsAndDry),
    MapEntry('flour', GroceryAisle.tinsAndDry),
    MapEntry('cornflour', GroceryAisle.tinsAndDry),
    MapEntry('cornstarch', GroceryAisle.tinsAndDry),
    MapEntry('breadcrumb', GroceryAisle.tinsAndDry),
    MapEntry('panko', GroceryAisle.tinsAndDry),
    MapEntry('baking powder', GroceryAisle.tinsAndDry),
    MapEntry('baking soda', GroceryAisle.tinsAndDry),
    MapEntry('bicarbonate', GroceryAisle.tinsAndDry),
    MapEntry('yeast', GroceryAisle.tinsAndDry),
    MapEntry('sugar', GroceryAisle.tinsAndDry),
    MapEntry('icing sugar', GroceryAisle.tinsAndDry),
    MapEntry('powdered sugar', GroceryAisle.tinsAndDry),
    MapEntry('confectioners sugar', GroceryAisle.tinsAndDry),
    MapEntry('caster sugar', GroceryAisle.tinsAndDry),
    MapEntry('granulated sugar', GroceryAisle.tinsAndDry),
    MapEntry('brown sugar', GroceryAisle.tinsAndDry),
    MapEntry('demerara', GroceryAisle.tinsAndDry),
    MapEntry('lentil', GroceryAisle.tinsAndDry),
    MapEntry('red lentil', GroceryAisle.tinsAndDry),
    MapEntry('green lentil', GroceryAisle.tinsAndDry),
    MapEntry('puy lentil', GroceryAisle.tinsAndDry),
    MapEntry('chickpea', GroceryAisle.tinsAndDry),
    MapEntry('kidney bean', GroceryAisle.tinsAndDry),
    MapEntry('black bean', GroceryAisle.tinsAndDry),
    MapEntry('cannellini', GroceryAisle.tinsAndDry),
    MapEntry('butter bean', GroceryAisle.tinsAndDry),
    MapEntry('baked bean', GroceryAisle.tinsAndDry),
    MapEntry('haricot', GroceryAisle.tinsAndDry),
    MapEntry('bean', GroceryAisle.tinsAndDry),
    MapEntry('stock cube', GroceryAisle.tinsAndDry),
    MapEntry('stock pot', GroceryAisle.tinsAndDry),
    MapEntry('chicken stock', GroceryAisle.tinsAndDry),
    MapEntry('beef stock', GroceryAisle.tinsAndDry),
    MapEntry('vegetable stock', GroceryAisle.tinsAndDry),
    MapEntry('stock', GroceryAisle.tinsAndDry),
    MapEntry('bouillon', GroceryAisle.tinsAndDry),
    MapEntry('oat', GroceryAisle.tinsAndDry),
    MapEntry('porridge', GroceryAisle.tinsAndDry),
    MapEntry('cereal', GroceryAisle.tinsAndDry),
    MapEntry('muesli', GroceryAisle.tinsAndDry),
    MapEntry('granola', GroceryAisle.tinsAndDry),
    MapEntry('almond', GroceryAisle.tinsAndDry),
    MapEntry('cashew', GroceryAisle.tinsAndDry),
    MapEntry('walnut', GroceryAisle.tinsAndDry),
    MapEntry('pecan', GroceryAisle.tinsAndDry),
    MapEntry('pistachio', GroceryAisle.tinsAndDry),
    MapEntry('pine nut', GroceryAisle.tinsAndDry),
    MapEntry('peanut', GroceryAisle.tinsAndDry),
    MapEntry('nut', GroceryAisle.tinsAndDry),
    MapEntry('seed', GroceryAisle.tinsAndDry),
    MapEntry('sesame seed', GroceryAisle.tinsAndDry),
    MapEntry('sunflower seed', GroceryAisle.tinsAndDry),
    MapEntry('chia seed', GroceryAisle.tinsAndDry),
    MapEntry('flaxseed', GroceryAisle.tinsAndDry),
    MapEntry('raisin', GroceryAisle.tinsAndDry),
    MapEntry('sultana', GroceryAisle.tinsAndDry),
    MapEntry('dried fruit', GroceryAisle.tinsAndDry),
    MapEntry('coconut cream', GroceryAisle.tinsAndDry),
    MapEntry('desiccated coconut', GroceryAisle.tinsAndDry),
    MapEntry('chocolate chip', GroceryAisle.tinsAndDry),
    MapEntry('cocoa', GroceryAisle.tinsAndDry),
    MapEntry('vanilla extract', GroceryAisle.tinsAndDry),
    MapEntry('vanilla essence', GroceryAisle.tinsAndDry),
    MapEntry('food colouring', GroceryAisle.tinsAndDry),
    MapEntry('food coloring', GroceryAisle.tinsAndDry),
    MapEntry('tuna', GroceryAisle.tinsAndDry),
    MapEntry('sardine', GroceryAisle.tinsAndDry),
    MapEntry('anchov', GroceryAisle.tinsAndDry),

    // ── Herbs & Spices (before produce — dried spices) ──
    MapEntry('garlic powder', GroceryAisle.spices),
    MapEntry('garlic granule', GroceryAisle.spices),
    MapEntry('onion powder', GroceryAisle.spices),
    MapEntry('chilli powder', GroceryAisle.spices),
    MapEntry('chili powder', GroceryAisle.spices),
    MapEntry('chilli flake', GroceryAisle.spices),
    MapEntry('chili flake', GroceryAisle.spices),
    MapEntry('red pepper flake', GroceryAisle.spices),
    MapEntry('cumin', GroceryAisle.spices),
    MapEntry('coriander seed', GroceryAisle.spices),
    MapEntry('ground coriander', GroceryAisle.spices),
    MapEntry('paprika', GroceryAisle.spices),
    MapEntry('smoked paprika', GroceryAisle.spices),
    MapEntry('turmeric', GroceryAisle.spices),
    MapEntry('cinnamon', GroceryAisle.spices),
    MapEntry('nutmeg', GroceryAisle.spices),
    MapEntry('ginger powder', GroceryAisle.spices),
    MapEntry('ground ginger', GroceryAisle.spices),
    MapEntry('clove', GroceryAisle.spices),
    MapEntry('cardamom', GroceryAisle.spices),
    MapEntry('star anise', GroceryAisle.spices),
    MapEntry('fennel seed', GroceryAisle.spices),
    MapEntry('mustard seed', GroceryAisle.spices),
    MapEntry('celery salt', GroceryAisle.spices),
    MapEntry('cayenne', GroceryAisle.spices),
    MapEntry('bay leaf', GroceryAisle.spices),
    MapEntry('bay leaves', GroceryAisle.spices),
    MapEntry('oregano', GroceryAisle.spices),
    MapEntry('dried thyme', GroceryAisle.spices),
    MapEntry('dried basil', GroceryAisle.spices),
    MapEntry('dried rosemary', GroceryAisle.spices),
    MapEntry('dried parsley', GroceryAisle.spices),
    MapEntry('dried oregano', GroceryAisle.spices),
    MapEntry('dried dill', GroceryAisle.spices),
    MapEntry('dried mint', GroceryAisle.spices),
    MapEntry('mixed herbs', GroceryAisle.spices),
    MapEntry('italian seasoning', GroceryAisle.spices),
    MapEntry('herbes de provence', GroceryAisle.spices),
    MapEntry('garam masala', GroceryAisle.spices),
    MapEntry('curry powder', GroceryAisle.spices),
    MapEntry('chinese five spice', GroceryAisle.spices),
    MapEntry('five spice', GroceryAisle.spices),
    MapEntry('allspice', GroceryAisle.spices),
    MapEntry('mixed spice', GroceryAisle.spices),
    MapEntry('ras el hanout', GroceryAisle.spices),
    MapEntry('sumac', GroceryAisle.spices),
    MapEntry('za\'atar', GroceryAisle.spices),
    MapEntry('zaatar', GroceryAisle.spices),
    MapEntry('saffron', GroceryAisle.spices),
    MapEntry('black pepper', GroceryAisle.spices),
    MapEntry('white pepper', GroceryAisle.spices),
    MapEntry('peppercorn', GroceryAisle.spices),
    MapEntry('salt', GroceryAisle.spices),
    MapEntry('sea salt', GroceryAisle.spices),
    MapEntry('flaky salt', GroceryAisle.spices),

    // ── Dairy & Eggs ──
    MapEntry('cream cheese', GroceryAisle.dairy),
    MapEntry('sour cream', GroceryAisle.dairy),
    MapEntry('double cream', GroceryAisle.dairy),
    MapEntry('single cream', GroceryAisle.dairy),
    MapEntry('whipping cream', GroceryAisle.dairy),
    MapEntry('heavy cream', GroceryAisle.dairy),
    MapEntry('clotted cream', GroceryAisle.dairy),
    MapEntry('creme fraiche', GroceryAisle.dairy),
    MapEntry('crème fraîche', GroceryAisle.dairy),
    MapEntry('cream', GroceryAisle.dairy),
    MapEntry('whole milk', GroceryAisle.dairy),
    MapEntry('semi-skimmed', GroceryAisle.dairy),
    MapEntry('skimmed milk', GroceryAisle.dairy),
    MapEntry('full fat milk', GroceryAisle.dairy),
    MapEntry('buttermilk', GroceryAisle.dairy),
    MapEntry('milk', GroceryAisle.dairy),
    MapEntry('cheddar', GroceryAisle.dairy),
    MapEntry('mozzarella', GroceryAisle.dairy),
    MapEntry('parmesan', GroceryAisle.dairy),
    MapEntry('parmigiano', GroceryAisle.dairy),
    MapEntry('gruyere', GroceryAisle.dairy),
    MapEntry('gruyère', GroceryAisle.dairy),
    MapEntry('feta', GroceryAisle.dairy),
    MapEntry('halloumi', GroceryAisle.dairy),
    MapEntry('brie', GroceryAisle.dairy),
    MapEntry('camembert', GroceryAisle.dairy),
    MapEntry('goat cheese', GroceryAisle.dairy),
    MapEntry('goat\'s cheese', GroceryAisle.dairy),
    MapEntry('ricotta', GroceryAisle.dairy),
    MapEntry('mascarpone', GroceryAisle.dairy),
    MapEntry('stilton', GroceryAisle.dairy),
    MapEntry('cheese', GroceryAisle.dairy),
    MapEntry('butter', GroceryAisle.dairy),
    MapEntry('margarine', GroceryAisle.dairy),
    MapEntry('yogurt', GroceryAisle.dairy),
    MapEntry('yoghurt', GroceryAisle.dairy),
    MapEntry('greek yogurt', GroceryAisle.dairy),
    MapEntry('greek yoghurt', GroceryAisle.dairy),
    MapEntry('egg', GroceryAisle.dairy),

    // ── Bakery ──
    MapEntry('sourdough', GroceryAisle.bakery),
    MapEntry('ciabatta', GroceryAisle.bakery),
    MapEntry('focaccia', GroceryAisle.bakery),
    MapEntry('baguette', GroceryAisle.bakery),
    MapEntry('brioche', GroceryAisle.bakery),
    MapEntry('bread', GroceryAisle.bakery),
    MapEntry('bread roll', GroceryAisle.bakery),
    MapEntry('dinner roll', GroceryAisle.bakery),
    MapEntry('rolls', GroceryAisle.bakery),
    MapEntry('bun', GroceryAisle.bakery),
    MapEntry('bagel', GroceryAisle.bakery),
    MapEntry('croissant', GroceryAisle.bakery),
    MapEntry('crumpet', GroceryAisle.bakery),
    MapEntry('english muffin', GroceryAisle.bakery),
    MapEntry('muffin', GroceryAisle.bakery),
    MapEntry('wrap', GroceryAisle.bakery),
    MapEntry('tortilla', GroceryAisle.bakery),
    MapEntry('pitta', GroceryAisle.bakery),
    MapEntry('pita', GroceryAisle.bakery),
    MapEntry('naan', GroceryAisle.bakery),
    MapEntry('flatbread', GroceryAisle.bakery),
    MapEntry('chapati', GroceryAisle.bakery),
    MapEntry('roti', GroceryAisle.bakery),
    MapEntry('pancake', GroceryAisle.bakery),
    MapEntry('waffle', GroceryAisle.bakery),

    // ── Meat & Fish ──
    MapEntry('chicken breast', GroceryAisle.meatAndFish),
    MapEntry('chicken thigh', GroceryAisle.meatAndFish),
    MapEntry('chicken drumstick', GroceryAisle.meatAndFish),
    MapEntry('chicken wing', GroceryAisle.meatAndFish),
    MapEntry('whole chicken', GroceryAisle.meatAndFish),
    MapEntry('chicken', GroceryAisle.meatAndFish),
    MapEntry('turkey', GroceryAisle.meatAndFish),
    MapEntry('duck', GroceryAisle.meatAndFish),
    MapEntry('beef mince', GroceryAisle.meatAndFish),
    MapEntry('lamb mince', GroceryAisle.meatAndFish),
    MapEntry('pork mince', GroceryAisle.meatAndFish),
    MapEntry('turkey mince', GroceryAisle.meatAndFish),
    MapEntry('mince', GroceryAisle.meatAndFish),
    MapEntry('ground beef', GroceryAisle.meatAndFish),
    MapEntry('ground turkey', GroceryAisle.meatAndFish),
    MapEntry('ground pork', GroceryAisle.meatAndFish),
    MapEntry('steak', GroceryAisle.meatAndFish),
    MapEntry('beef', GroceryAisle.meatAndFish),
    MapEntry('sirloin', GroceryAisle.meatAndFish),
    MapEntry('ribeye', GroceryAisle.meatAndFish),
    MapEntry('brisket', GroceryAisle.meatAndFish),
    MapEntry('pork chop', GroceryAisle.meatAndFish),
    MapEntry('pork loin', GroceryAisle.meatAndFish),
    MapEntry('pork belly', GroceryAisle.meatAndFish),
    MapEntry('pork', GroceryAisle.meatAndFish),
    MapEntry('bacon', GroceryAisle.meatAndFish),
    MapEntry('ham', GroceryAisle.meatAndFish),
    MapEntry('gammon', GroceryAisle.meatAndFish),
    MapEntry('prosciutto', GroceryAisle.meatAndFish),
    MapEntry('chorizo', GroceryAisle.meatAndFish),
    MapEntry('salami', GroceryAisle.meatAndFish),
    MapEntry('pepperoni', GroceryAisle.meatAndFish),
    MapEntry('sausage', GroceryAisle.meatAndFish),
    MapEntry('lamb chop', GroceryAisle.meatAndFish),
    MapEntry('lamb leg', GroceryAisle.meatAndFish),
    MapEntry('lamb shoulder', GroceryAisle.meatAndFish),
    MapEntry('lamb', GroceryAisle.meatAndFish),
    MapEntry('veal', GroceryAisle.meatAndFish),
    MapEntry('venison', GroceryAisle.meatAndFish),
    MapEntry('salmon', GroceryAisle.meatAndFish),
    MapEntry('cod', GroceryAisle.meatAndFish),
    MapEntry('haddock', GroceryAisle.meatAndFish),
    MapEntry('sea bass', GroceryAisle.meatAndFish),
    MapEntry('mackerel', GroceryAisle.meatAndFish),
    MapEntry('trout', GroceryAisle.meatAndFish),
    MapEntry('tuna steak', GroceryAisle.meatAndFish),
    MapEntry('fish', GroceryAisle.meatAndFish),
    MapEntry('prawn', GroceryAisle.meatAndFish),
    MapEntry('shrimp', GroceryAisle.meatAndFish),
    MapEntry('king prawn', GroceryAisle.meatAndFish),
    MapEntry('scallop', GroceryAisle.meatAndFish),
    MapEntry('mussel', GroceryAisle.meatAndFish),
    MapEntry('clam', GroceryAisle.meatAndFish),
    MapEntry('squid', GroceryAisle.meatAndFish),
    MapEntry('calamari', GroceryAisle.meatAndFish),
    MapEntry('crab', GroceryAisle.meatAndFish),
    MapEntry('lobster', GroceryAisle.meatAndFish),
    MapEntry('tofu', GroceryAisle.meatAndFish),
    MapEntry('tempeh', GroceryAisle.meatAndFish),

    // ── Produce (last among food aisles — broadest matches) ──
    MapEntry('fresh basil', GroceryAisle.produce),
    MapEntry('fresh mint', GroceryAisle.produce),
    MapEntry('fresh parsley', GroceryAisle.produce),
    MapEntry('fresh coriander', GroceryAisle.produce),
    MapEntry('fresh cilantro', GroceryAisle.produce),
    MapEntry('fresh thyme', GroceryAisle.produce),
    MapEntry('fresh rosemary', GroceryAisle.produce),
    MapEntry('fresh dill', GroceryAisle.produce),
    MapEntry('fresh chive', GroceryAisle.produce),
    MapEntry('fresh herb', GroceryAisle.produce),
    MapEntry('basil', GroceryAisle.produce),
    MapEntry('mint', GroceryAisle.produce),
    MapEntry('parsley', GroceryAisle.produce),
    MapEntry('coriander', GroceryAisle.produce),
    MapEntry('cilantro', GroceryAisle.produce),
    MapEntry('thyme', GroceryAisle.produce),
    MapEntry('rosemary', GroceryAisle.produce),
    MapEntry('dill', GroceryAisle.produce),
    MapEntry('chive', GroceryAisle.produce),
    MapEntry('sage', GroceryAisle.produce),
    MapEntry('tarragon', GroceryAisle.produce),
    MapEntry('apple', GroceryAisle.produce),
    MapEntry('banana', GroceryAisle.produce),
    MapEntry('orange', GroceryAisle.produce),
    MapEntry('lemon', GroceryAisle.produce),
    MapEntry('lime', GroceryAisle.produce),
    MapEntry('grape', GroceryAisle.produce),
    MapEntry('strawberr', GroceryAisle.produce),
    MapEntry('blueberr', GroceryAisle.produce),
    MapEntry('raspberr', GroceryAisle.produce),
    MapEntry('blackberr', GroceryAisle.produce),
    MapEntry('cherry', GroceryAisle.produce),
    MapEntry('cherries', GroceryAisle.produce),
    MapEntry('peach', GroceryAisle.produce),
    MapEntry('plum', GroceryAisle.produce),
    MapEntry('pear', GroceryAisle.produce),
    MapEntry('mango', GroceryAisle.produce),
    MapEntry('pineapple', GroceryAisle.produce),
    MapEntry('melon', GroceryAisle.produce),
    MapEntry('watermelon', GroceryAisle.produce),
    MapEntry('kiwi', GroceryAisle.produce),
    MapEntry('avocado', GroceryAisle.produce),
    MapEntry('coconut', GroceryAisle.produce),
    MapEntry('pomegranate', GroceryAisle.produce),
    MapEntry('fig', GroceryAisle.produce),
    MapEntry('passion fruit', GroceryAisle.produce),
    MapEntry('nectarine', GroceryAisle.produce),
    MapEntry('apricot', GroceryAisle.produce),
    MapEntry('tomato', GroceryAisle.produce),
    MapEntry('onion', GroceryAisle.produce),
    MapEntry('garlic', GroceryAisle.produce),
    MapEntry('ginger', GroceryAisle.produce),
    MapEntry('potato', GroceryAisle.produce),
    MapEntry('sweet potato', GroceryAisle.produce),
    MapEntry('carrot', GroceryAisle.produce),
    MapEntry('broccoli', GroceryAisle.produce),
    MapEntry('cauliflower', GroceryAisle.produce),
    MapEntry('cabbage', GroceryAisle.produce),
    MapEntry('spinach', GroceryAisle.produce),
    MapEntry('kale', GroceryAisle.produce),
    MapEntry('lettuce', GroceryAisle.produce),
    MapEntry('rocket', GroceryAisle.produce),
    MapEntry('arugula', GroceryAisle.produce),
    MapEntry('watercress', GroceryAisle.produce),
    MapEntry('salad', GroceryAisle.produce),
    MapEntry('cucumber', GroceryAisle.produce),
    MapEntry('pepper', GroceryAisle.produce),
    MapEntry('bell pepper', GroceryAisle.produce),
    MapEntry('capsicum', GroceryAisle.produce),
    MapEntry('chilli', GroceryAisle.produce),
    MapEntry('chili', GroceryAisle.produce),
    MapEntry('jalapeño', GroceryAisle.produce),
    MapEntry('jalapeno', GroceryAisle.produce),
    MapEntry('courgette', GroceryAisle.produce),
    MapEntry('zucchini', GroceryAisle.produce),
    MapEntry('aubergine', GroceryAisle.produce),
    MapEntry('eggplant', GroceryAisle.produce),
    MapEntry('mushroom', GroceryAisle.produce),
    MapEntry('leek', GroceryAisle.produce),
    MapEntry('celery', GroceryAisle.produce),
    MapEntry('sweetcorn', GroceryAisle.produce),
    MapEntry('corn on the cob', GroceryAisle.produce),
    MapEntry('asparagus', GroceryAisle.produce),
    MapEntry('green bean', GroceryAisle.produce),
    MapEntry('runner bean', GroceryAisle.produce),
    MapEntry('mange tout', GroceryAisle.produce),
    MapEntry('snap pea', GroceryAisle.produce),
    MapEntry('sugar snap', GroceryAisle.produce),
    MapEntry('pea', GroceryAisle.produce),
    MapEntry('beetroot', GroceryAisle.produce),
    MapEntry('beet', GroceryAisle.produce),
    MapEntry('turnip', GroceryAisle.produce),
    MapEntry('parsnip', GroceryAisle.produce),
    MapEntry('swede', GroceryAisle.produce),
    MapEntry('rutabaga', GroceryAisle.produce),
    MapEntry('radish', GroceryAisle.produce),
    MapEntry('spring onion', GroceryAisle.produce),
    MapEntry('scallion', GroceryAisle.produce),
    MapEntry('green onion', GroceryAisle.produce),
    MapEntry('shallot', GroceryAisle.produce),
    MapEntry('fennel', GroceryAisle.produce),
    MapEntry('artichoke', GroceryAisle.produce),
    MapEntry('butternut squash', GroceryAisle.produce),
    MapEntry('acorn squash', GroceryAisle.produce),
    MapEntry('spaghetti squash', GroceryAisle.produce),
    MapEntry('squash', GroceryAisle.produce),
    MapEntry('pumpkin', GroceryAisle.produce),
    MapEntry('bok choy', GroceryAisle.produce),
    MapEntry('pak choi', GroceryAisle.produce),
    MapEntry('bean sprout', GroceryAisle.produce),
    MapEntry('edamame', GroceryAisle.produce),
    MapEntry('lemongrass', GroceryAisle.produce),
  ];

  /// Classify an ingredient name into a grocery aisle.
  ///
  /// Normalises the name (lowercase, trim) and checks against a keyword map
  /// ordered from most specific to least specific. Returns [GroceryAisle.other]
  /// if no keyword matches.
  static GroceryAisle classify(String ingredientName) {
    final name = ingredientName.toLowerCase().trim();
    if (name.isEmpty) return GroceryAisle.other;

    for (final entry in _keywords) {
      if (name.contains(entry.key)) {
        return entry.value;
      }
    }

    return GroceryAisle.other;
  }
}
